---
title: "hw5"
author: "Renee Wang UNI:hw2851"
date: "11/20/2021"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)
library(reshape2)
```

---
title: "Homework 5"
output: github_document
---

```{r setup, include = FALSE}
library(tidyverse)
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


## Problem 1

Read in the data.

```{r}
homicide_df = 
  read_csv("./data/homicide-data.csv", na = c("","Unknown")) %>%
  mutate(city_state = str_c(city, state),
         resolution = case_when(
              disposition == "Closed without arrest" ~ "unsolved",
              disposition == "Open/No arrest"        ~ "unsolved",
              disposition == "Closed by arrest"      ~ "solved")) %>%
  relocate(city_state) %>%
  filter(city_state != "Tulsa_AL")
```

```{r}
baltimore_df =
  homicide_df %>%
  filter(city_state == "BaltimoreMD")

baltimore_summary =
  baltimore_df %>%
  summarize(
    unsolved = sum(resolution == "unsolved"),
    n = n()
  )

baltimore_test =
  prop.test(
    x = baltimore_summary %>% pull(unsolved),
    n = baltimore_summary %>% pull(n))

baltimore_test %>%
  broom::tidy()  
```

# Problem2
```{r}
csv_list =
 tibble(
  files = list.files("./data/zip_data/"))


readcsv = function(csv){
 paste("./data/zip_data",csv,sep="/")  %>%
   read.csv()}


results = map(csv_list$files, readcsv)

csv_df = c(csv_list, results)
names(csv_df)[2] = "results"


# colsplit(csv_df$files,"_", names=c(control_arm, subject_id))
  


  
      
```